### ISSUE TITLE
Navigation Router

### ISSUE THREAD

**Issue by grahammendick** [vinej/react-remux#1]
I'm getting in touch to thank you for your [kind comment about my Navigation router](https://github.com/trueadm/inferno/issues/274#issuecomment-232492079) and to suggest a way to shorten your navigation.js code. You can merge the code in your separate `navigated` functions into a single `onNavigate` handler.

The states in the Navigation router configuration accept custom properties. You can add your component and display properties onto them:

```
var stateNavigator = new StateNavigator([
    {key: 'todos', route: 'todos', component: <Todos store={todoStore} />, display: 'block' },
    {key: 'welcome', route: '', component: <Welcome />, display: 'block' }
]);
```

Then you can add an `onNavigate` handler that extracts the custom properties from the current state and calls your `routeAdd` function. The handler's called every time a state is navigated to.

```
stateNavigator.onNavigate((oldState, state, data) => {
    RouteActions.routeAdd({
        id: state.key,
        component: () => state.component,
        display: state.display
    });
});
```

**Comment by vinej** [comment]
hello

I did the modifications

Thanks very much

**Comment by vinej** [comment]
Modification done
